---
resources:

- name: "Links"
  type: git

- name: "Compiled Releases"
  type: git

- name: "bosh.io/releases"
  type: git


jobs:
- name: "Release 2.0"
  public: true
  plan:
  
  - put: "Links"
  
  - put: "Compiled Releases"
  
  - put: "bosh.io/releases"
  

