---
resources:

- name: "Docs 2.0"
  type: git

- name: "Release 2.0"
  type: git

- name: "Manifest 2.0"
  type: git

- name: "Stemcell 2.0"
  type: git

- name: "Much More 2.0s"
  type: git


jobs:
- name: "BOSH 2.0"
  public: true
  plan:
  
  - put: "Docs 2.0"
  
  - put: "Release 2.0"
  
  - put: "Manifest 2.0"
  
  - put: "Stemcell 2.0"
  
  - put: "Much More 2.0s"
  

